language: rust

sudo: required

matrix:
  include:
    - rust: stable
    - rust: beta
    - rust: nightly

branches:
  only:
    - master

script:
  - |
      cargo test --verbose

before_install:
  - sudo apt-get update

addons:
  apt:
    packages:
      - libcurl4-openssl-dev
      - libelf-dev
      - libdw-dev
      - cmake
      - gcc
      - binutils-dev
